MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.3"                 # [osx and x86_64]
c_compiler_version:            # [osx]
  - 16                         # [osx]
cxx_compiler_version:          # [osx]
  - 16                         # [osx]
